### ISSUE TITLE
Decouple RNG from MathAdapter

### ISSUE THREAD

**Issue by aztech-dev** [mdanter/phpecc#29]
Currently, the RNG used to generate private keys is directly coupled to the MathAdapter implementation:

- BCMath uses `mt_rand`, which is not suited for crypto (ref http://php.net/manual/fr/function.mt-rand.php)
- GMP uses gmp_random, which internally uses `mpz_urandomb` from the C library

It would be better to separate both concerns (math ops vs. rng). It would allow for example to use openssl_random_pseudo_bytes() or an external lib (I'm thinking ircmaxell/randomlib) to provide better randoms, independantly of the used math library.

Thoughts before I start coding on this issue ?

**Comment by aztech-dev** [comment]
Ok, I've created a P/R extracting RNG, a review is of course welcome, and once it's merged, you can add your deterministic signature implementation.

**Comment by afk11** [comment]
Nice, looks good. I'll whip it up in a few, I have it already written for another library with tests too.

**Comment by aztech-dev** [comment]
Actually, this one's done...
