### ISSUE TITLE
Abstracted EcMath class?

### ISSUE THREAD

**Issue by afk11** [mdanter/phpecc#30]
I've been thinking about writing a wrapper for the Math classes which would support taking either a Point, or an integer, and allowing the library to apply the relevant arithmetic operations based on whatever it's acting on. 

ECDSA supports deterministic algorithms to calculate public keys from a master public key. This master public key is the result of k * G, where k is your master private key for a sequence of addresses.

The master public key is used to deterministically derive a unique offset through hashing, meaning you can add this offset to a master private key, or convert to a point and add it to a master public key, yielding child public keys. 

The thing is, regardless if you're operating on a point (you only had the master public key) or an integer (you had a private key) the operations are the exact same: Simply add two integers or points together

You'll see that the private case requires mod() after adding two integers together. This happens everywhere in the library. 

Private:
```
  $privKey = Math::hexDec(openssl_random_pseudo_bytes(32))
  $offset = Math:hexDec(hash(..))

  $childKey = 
Math::mod(
  Math::add(
    $offset, 
    $privKey
  )
  $curveOrder
);
```

Or a public case:
```
  $generator = new GeneratorPoint(..);

  $offset = Math::hexDec(hash(..));
  $offset = $generator->mul($offset);

  $pubkey = new Point(..);
  $newKey = $pubkey->add($offset);
```
This is a minor example, though could help reduce the level of code in other places in the library (Wherever math::add(), and math::mul() occur are often followed by math::mod(), so this class would handle that internally if required)

The homomorphic properties of points on an elliptic curve, and integers mod q, mean these operations should be abstractable:

```
  $offsetSrc = ... A point, or integer.
  $keySrc = .. a point, or integer

  $offset = new EcMath($offsetSrc);
  $key = new EcMath($startKey)
  $child = $key->add($offset);
```

I can whip something up for this, just wondering what you all think. No sense duplicating code just because you happen to be dealing with a point (publickey) or integer (privatekey) at the time.

**Comment by btcdrak** [comment]
bump

**Comment by btcdrak** [comment]
bump

**Comment by btcdrak** [comment]
bump

**Comment by btcdrak** [comment]
bump

**Comment by afk11** [comment]
My main intention here was the EcMath class, but can give larger refactoring a shot. I have some questions about which classes should stay in the root namespace.. but otherwise can plough on!

**Comment by btcdrak** [comment]
That sounds ok. I'm just trying to get BC breaks out of the way before next release.

**Comment by afk11** [comment]
This has been merged, and the large refactoring also!
