### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by FabioCarpi** [mdanter/phpecc#37]
I'm writing this because i don't found a way to communicate with you, guys.
I want to know, how to verify a signed transaction in bitcoin.
In my case, i have the scriptsig (r and s) and the pubkey
running the script (https://en.bitcoin.it/wiki/Script) how i can verify that?

**Comment by rubensayshi** [comment]
hey @FabioCarpi you should look at the https://github.com/Bit-Wasp/bitcoin-lib-php repo
it uses this library to do almost all the bitcoin stuff you could possibly need!
Or you could just take a look at the code in there to see how it uses this library to do so!

Also you can reach me on irc.freenode.net - I'm rubensayshi and am in #bitcoin

**Comment by FabioCarpi** [comment]
I'm already using this library. This help me so much.
but, in bitcoin-qt to verify the sign, he have to hash the tx again?

**Comment by aztech-dev** [comment]
This is not the correct repo for this issue... cc @btcdrak

**Comment by btcdrak** [comment]
Using bitcoin-qt/bitcoin-cli/RPC you use `verifymessage`.
