### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by aztech-dev** [mdanter/phpecc#42]
-- note: this is more a reminder for me to do it than to raise a real issue, but my free time is limited so can't tackle it right now --

- [X] Update key exchange example
- [X] Document console commands
- [ ] Warn about usage of insecure RNG's

**Comment by btcdrak** [comment]
bump

**Comment by aztech-dev** [comment]
Readme's good now, default mode is to use best RNG available by default, and since mcrypt is required by composer.json, the default install ensures decent random number generation.
