### ISSUE TITLE
PHP version requirement bump ?

### ISSUE THREAD

**Issue by aztech-dev** [mdanter/phpecc#45]
As you may be aware, PHP 5.3.3 is no longer officially supported.

I think it's decent to follow the supported versions, and drop support for EOL'ed versions.

Also, README.md currently states PHP 5.4 as min version, while composer enforces 5.3.3 . However, the library is currently not tested under 5.3.3 (ref .travis.yml)

I'm all for bumping composer.json to 5.4, but I think consensus should be reached before doing so:
- Option A: keep supporting 5.3.3, add 5.3 to travis file, and work through the potential issues that may have been introduced in the recent commits but were not tested against 5.3
- Option B: drop 5.3.3 and move on with the future (no, I'm not the very least biased), bump composer.json to 5.4 and done.

**Comment by btcdrak** [comment]
I have no problem bumping to 5.4 especially because anyone using these libraries would have to be using a dedicated/VM environment anyway.
