### ISSUE TITLE
Installation by composer fails at the moment

### ISSUE THREAD

**Issue by afk11** [mdanter/phpecc#53]
Tried to install this through composer instead of a clone and it failed, seems to be because it can't find the phpasn1 commit

@aztech-dev 
```
  Problem 1
    - Installation request for mdanter/ecc dev-master -> satisfiable by mdanter/ecc[dev-master].
    - mdanter/ecc dev-master requires fgrosse/phpasn1 dev-master#1033ca99966ee75b957d6f923dc21f4dad9b334b -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by aztech-dev** [comment]
Erf, now that's another issue, forgot about that detail... Basically, Composer does not read repositories defined in composer.json files of dependencies. I've opened an issue with @FGrosse to see if he can register it in packagist, which would solve the problem.

Temporary workaround is to add the repositories config from this repo to the composer.json of your project where you're trying to install.
