### ISSUE TITLE
Next Major Release 0.3.0

### ISSUE THREAD

**Issue by btcdrak** [mdanter/phpecc#59]
I would like to start thinking about a major version release of this library given we have had some BC breaks in the API. Let's have a discussion about what is necessary.

**Comment by aztech-dev** [comment]
Hum, I think solving #47 is a must for next release, as well as getting #28 thoroughly reviewed (volunteers ? -- I am obviously the wrong person to do it).

A bit of a documentation effort would not hurt also...

**Comment by btcdrak** [comment]
I have opened up some milestones so we can more easily track.

**Comment by btcdrak** [comment]
ping @afk11 @rubensayshi

**Comment by aztech-dev** [comment]
I think you can #64 to the milestone

**Comment by afk11** [comment]
https://github.com/mdanter/phpecc/pull/80 can probably be merged today
https://github.com/mdanter/phpecc/issues/81 will be done today. 

How does everyone find the API? If it's set in stone we can release 0.3.0, and follow up with tests + small CLI feature's. 

https://github.com/mdanter/phpecc/issues/47  - are we actually able to test EcDH when we base64_encode the message, and hash the secretKey->getX?

**Comment by afk11** [comment]
@rubensayshi @aztech-dev

**Comment by btcdrak** [comment]
Are we ready to tag this release?

**Comment by btcdrak** [comment]
0.3.0 has been released.
