### ISSUE TITLE
Extract MathAdapter to another lib ?

### ISSUE THREAD

**Issue by aztech-dev** [mdanter/phpecc#63]
What would you think of completely extracting the MathAdapter stuff to its own, standalone library ?

**Comment by btcdrak** [comment]
IMO better develop it here, and see if it makes sense later.

**Comment by aztech-dev** [comment]
There's definitely no rush. I had 0.4.0 in mind for that...

**Comment by aztech-dev** [comment]
PS but it does make sense to me to separate into two components, as it would mean potentially allowing use of other libraries and moving the gmp requirement out of this lib, which in essence is only required for the bignum stuff
