### ISSUE TITLE
docblocks

### ISSUE THREAD

**Issue by rubensayshi** [mdanter/phpecc#70]
I'd do a PR to fix it but before I spend time on it I'm curious if there might be a reason (personal prefence or smt) for it ...

why is the following (in `src/Point.php`):

```php
    /*
     * (non-PHPdoc) @see \Mdanter\Ecc\PointInterface::mul()
     */
    public function mul($n)
``` 

not like;

```php
    /**
     * @see \Mdanter\Ecc\PointInterface::mul()
     */
    public function mul($multiplier)
``` 

- using `/**` so IDEs will use it for the function
- removing the `(non-PHPdoc)` so the `@see` is actually parsed
- matching the argument name to the `PointInterface`

if there's no particular reason why you guys prefer it this way then I'll go and clean it up, because I personally like it a lot better when my IDE (phpstorm in my case) properly parses the docblocks and as a result gives better code intel

**Comment by aztech-dev** [comment]
Go ahead :)

**Comment by rubensayshi** [comment]
afaik `@see` is a proper PHPdoc so the `(non-PHPdoc)` that is all over the place can be all removed, right @btcdrak ?

**Comment by rubensayshi** [comment]
actually seems it should be `@inheritDoc`

**Comment by rubensayshi** [comment]
bleh  
`@inheritDoc` fixes IDE complaining about missing arguments in docblock, but it's not clickable   `@see` allows you to CTRL+click on it to take you to the interface, but IDE complains about undocumented arguments :/

**Comment by aztech-dev** [comment]
Put both then :D
Le 19 févr. 2015 11:53, "Ruben de Vries" <notifications@github.com> a écrit
:

**Comment by aztech-dev** [comment]
Actually, I think the proper solution would be:

```
/**
 * @inheritdoc
 * @see Interface::method()
 */

@inheritdoc is meant to include tags from the parent method, while @see is meant to create a link to a code element.

**Comment by rubensayshi** [comment]
yea you're right, see https://github.com/mdanter/phpecc/pull/71
