### ISSUE TITLE
KeyStorage class of some kind?

### ISSUE THREAD

**Issue by afk11** [mdanter/phpecc#76]
It's a bit unclear what's happening here, though thinking a KeyStorage class could help with persisting classes, and giving some simplified interface to loading/persisting keys of different types? 

    use \Mdanter\Ecc\File\PemLoader;
    use \Mdanter\Ecc\Serializer\PrivateKey\DerPrivateKeySerializer;
    use \Mdanter\Ecc\Serializer\PrivateKey\PemPrivateKeySerializer;
    use \Mdanter\Ecc\Serializer\PublicKey\DerPublicKeySerializer;
    use \Mdanter\Ecc\Serializer\PublicKey\PemPublicKeySerializer;

    $loader = new PemLoader();
    $privKeySerializer = new PemPrivateKeySerializer(new DerPrivateKeySerializer());
    $pubKeySerializer = new PemPublicKeySerializer(new DerPublicKeySerializer());

**Comment by afk11** [comment]
Also it could support password protected private keys? :D

**Comment by aztech-dev** [comment]
It's pretty clear to me, and it's called composition :p

But you're right, something along these lines would cut it probably, though I'd rather see a FileReader and a FileWriter:

```
use \Mdanter\Ecc\File\FileReader;
use \Mdanter\Ecc\File\FileWriter;

// Read from file
$reader = new FileReader();
$key = $reader->loadPem('path/to/key.pem');

// Write to file
$writer = new FileWriter();
$writer->writePem('path/to/key.pem', $key);
```

Or taking it a step further, detect the serializer type based on detected extension on the filename. And yes, password protection is something I had in mind also, alas my days are only 24 hours long :(

**Comment by afk11** [comment]
I will close this for now, things are probably fine the way they are :)
