### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by Spomky** [mdanter/phpecc#88]
Hi all,

It seems you are ready to tag a new major release.
The tag will be `v0.3.0` as suggested in issue #59.
The next major release appears to be `v0.4.0`(#83)

For all my projects, I follow the semantic versioning descibed [on this page](http://semver.org/), even for small projects.
The version numbers follow a logic that is easy to understand and to implement with (IMHO) great benefits.

I will be great if this project is tagged following this semantic versioning.

What do you think?

**Comment by btcdrak** [comment]
Yes, we already follow SemVer.

**Comment by btcdrak** [comment]
`v0.3.0` has been released.
